top_srcdir   = /root/devel/php-4.2.0
top_builddir = /root/devel/php-4.2.0
srcdir       = /root/devel/php-4.2.0/ext/sqlite
builddir     = /root/devel/php-4.2.0/ext/sqlite
VPATH        = /root/devel/php-4.2.0/ext/sqlite
# $Id$

LTLIBRARY_NAME        = libsqlite.la
LTLIBRARY_SOURCES     = sqlite.c
LTLIBRARY_SHARED_NAME = sqlite.la
LTLIBRARY_SHARED_LIBADD  = $(SQLITE_SHARED_LIBADD)

include $(top_srcdir)/build/dynlib.mk
